# Run r cmd check
name: call-r-cmd-check
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
# The default build trigger is to run the action on every push and pull request, for any branch
  push:
  pull_request:
  # To run the default repository branch weekly on sunday, uncomment the following 2 lines
  #schedule:
    #- cron: '0 0 * * 0'
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/r-cmd-check.yml@main
