# Render readme, based on 
# https://raw.githubusercontent.com/r-lib/actions/master/.github/workflows/render-readme.yaml
name: Render README
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - 'README.Rmd'

jobs:
  render:
    name: Render README
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rmarkdown
            any::devtools
      - name: Install local package
        run: |
          devtools::install_local(".")
        shell: Rscript {0}
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'docs: update readme'
          branch: update-readme
          title: 'Update readme'
          body: |
           Auto-generated by [render-readme.yml](https://github.com/nmfs-fish-tools/nmfspalette/tree/main/.github/workflows/render-readme.yml).
        
